### ISSUE TITLE
Change Font import from Fira Code to Hack

### ISSUE THREAD

**Issue by Novalis15** [js-sadness/js-sadness.github.io#18]
We are still importing `Fira Code`, however we try to use `Hack`, which is not imported:

https://github.com/js-sadness/js-sadness.github.io/blob/78663baf9e3073fd2eff88a18b927e2bac9e9c03/_layouts/default.html#L14
https://github.com/js-sadness/js-sadness.github.io/blob/78663baf9e3073fd2eff88a18b927e2bac9e9c03/style.sass#L23

**Comment by deflectn** [comment]
🥸
