### ISSUE TITLE
Adding a highlighter

### ISSUE THREAD

**Issue by Novalis15** [js-sadness/js-sadness.github.io#5]
What do you think about using a syntax highlighter like [Rouge](http://rouge.jneen.net)?
Code would be highlighted correctly and therefore displayed more clear, so people can be sad about javascript in a less confused way.

**Comment by Novalis15** [comment]
This [link](http://sangsoonam.github.io/2019/01/20/syntax-highlighting-in-jekyll.html) might help with setting that up.

**Comment by js-sadness** [comment]
Jekyll already supports syntax highlighting - the css just has not yet been added. Adding the css would be less work than adding rouge, I think, so let's use that css instead, ok?

**Comment by js-sadness** [comment]
consider reopening this issue if the current syntax highlighting is not sufficient
